name: tfsec

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run tfsec
        id: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true

      - name: Post tfsec results as PR comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v6
        with:
          script: |
            let output = '';
            await github.exec('tfsec', [], {
              listeners: {
                stdout: (data) => {
                  output += data.toString();
                },
              },
            });
            const comment = `
            ## tfsec Scan Results
            \`\`\`
            ${output}
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: github.context.issue.number,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              body: comment,
            });